### ISSUE TITLE
doesn't compile?

### ISSUE THREAD

**Issue by BMaxV** [Suloch/chirp#18]
doesn't compile?

**Comment by Suloch** [comment]
what compiler are you using?
It does on gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2)

**Comment by BMaxV** [comment]
Hi, thank you for the quick answer!

I don't know, good question, I will check later. I just used "make" as instructed and it didn't work.

**Comment by BMaxV** [comment]
Hey, I'm back, no idea what it was last time, but *that* works now and some of the sample programs work as well.
