### ISSUE TITLE
Single quotes aren't recognized 

### ISSUE THREAD

**Issue by mimi89999** [Suloch/chirp#9]
Rockstar language specification states that [`'s\W+` should be replaced with ` is `](https://codewithrockstar.com/docs#single-quotes), but _chirp_ doesn't recognize them:

```
(chirp)>>Janie's got a gun
syntax error
invalid character
invalid character
(chirp)>>Union's been on strike
invalid character
```

**Comment by Suloch** [comment]
Sorry for the extra late reply.
Thanks for letting me know.
I fixed it, it is working now.
![image](https://user-images.githubusercontent.com/10083311/69541814-19384400-0fb0-11ea-91d2-f47a9cc80e5b.png)
